mysite/project/apps/account/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model

from . import views
from .forms import ProfileForm, ProfileFormHead, ProfileFormPhoto, ChangeEmail

app_name = 'account'

urlpatterns = [

    path('p/<slug:login>/', views.ProfileView.as_view(form_class=ProfileForm),
         {'location': 'profile', 'title_user': True}, name='profile'),

    path('p/<slug:login>/post/<int:init>/', views.ProfileView.as_view(form_class=ProfileForm),
         {'location': 'profile', 'title_user': True}, name='profile-post'),



    path('settings/', TemplateView.as_view(template_name='account/settings.html'),
         {'title': 'Settings'}, name='profile-settings'),

    path('settings/change-pass/', views.MyPasswordChangeView.as_view(success_url='/'), name='change-pass'),

    path('settings/change-email/', views.MyEmailChangeView.as_view(success_url='/',
                                                                   model = get_user_model(),
                                                                   form_class = ChangeEmail
                                                                    ), name='change-email'),

    path('p/<slug:login>/change/head/', views.ProfileView.as_view(form_class=ProfileFormHead),
         {'location': 'profile'}, name='change-head'),

    path('p/<slug:login>/change/image/', views.ProfileView.as_view(form_class=ProfileFormPhoto),
         {'event': 'photo', 'location': 'profile'}, name='change-photo'),

    path('p/<slug:login>/<path:location>/', views.ProfileView.as_view(form_class=ProfileForm),
          {'title_user': True}),



]

mysite/project/apps/blog/urls.py
from django.urls import path
from . import views
from .models import  Article
from .forms import CreatePostForm, UpdatePostForm
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [

    path('', RedirectView.as_view(pattern_name='blog:main_page')),

    path('m/', views.MainPage.as_view(template_name = 'blog/MainPage.html'),
         {'location': 'top', 'title': 'Signup: Main page'},
         name='main_page'),

    path('home/', login_required(views.MainPage.as_view(template_name = 'blog/Home.html')),
         {'template_name': 'blog/Home.html', 'location': 'home', 'title': 'Home'},
         name='home'),

    path('create-post/', views.CreateArticle.as_view(form_class=CreatePostForm, model=Article, success_url = '/'),
         name='create_post'),

    path('update-post/<int:pk>/', views.UpdateArticle.as_view(form_class=UpdatePostForm,
         template_name='blog/update_post.html', model=Article, success_url = '/'),
         name='update_post'),

    path('api/post/detail-post/<int:pk>/', views.DetailArticle.as_view(model=Article,
                                                                       template_name = 'blog/articles.html')),

    path('api/home/recommends/', views.Recommend.as_view()),

    path('m/<path:location>/', views.MainPage.as_view(template_name = 'blog/MainPage.html'),
         {'title': 'Signup: Main page'}),
]

mysite/project/apps/info/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views, forms

app_name = 'info'

urlpatterns = [
    path('load_template/<path:url>/', views.Info.as_view()),
    path('send/message/', views.QuestionView.as_view(template_name='info/site_form.html',
                                                     form_class=forms.QuestionForm),
                                                    {'type': 'msg'}, name='send-message'),
    path('send/email/', views.QuestionView.as_view(template_name='info/email_form.html',
                                                   form_class=forms.QuestionFormEmail),
                                                    {'type': 'email'}, name='send-email'),

    path('<path:url>/', views.Info.as_view(template_name='info/info-main.html'), {'title': 'info'}, name="dispatch"),

]

mysite/project/apps/myauth/urls.py
from django.urls import path
from . import views
from .forms import MyPasswordResetForm, MySetPasswordForm,  MyLoginForm, ActivEmail, MyRegForm
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth import get_user_model

app_name = 'myauth'

urlpatterns = [

    path('login/', views.Login.as_view(template_name = 'myauth/registration.html',
                                       form_class = MyLoginForm),
                                        {'title': 'Login'},
                                        name='login'),

    path('registration/', views.Registr.as_view(template_name = 'myauth/registration.html',
                                        form_class = MyRegForm,
                                        model=get_user_model(),
                                        success_url='/'),
                                        {'title': 'Registration'},
                                        name='registration'),

    path('login/password-reset/', views.ResetPass.as_view(success_url = '/login/',
                                        email_template_name='back_task/reset_mail.html',
                                        html_email_template_name='back_task/reset_mail.html',
                                        form_class=MyPasswordResetForm)),

    path('login/help/', views.HelpLogin.as_view(template_name = 'myauth/help.html',
                                        form_class = ActivEmail,
                                        success_url='/login/help/'),
                                        {'title': 'Help'},
                                        name='login-help'),

    path('login/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                        template_name = 'myauth/reset_pass_form.html',
                                        success_url='/login/',
                                        form_class=MySetPasswordForm),
                                        name='password_reset_confirm'),

    path('logout/', views.Logout.as_view(template_name = 'myauth/registration.html',
                                        next_page = '/'),
                                        name='logout'),
    path('verify/<uuid:uuid>/', views.Vertify_account.as_view(), name='verify'),



]

mysite/project/apps/search/urls.py
from django.urls import path
from . import views
from project.apps.blog.models import Article
from django.contrib.auth import get_user_model

app_name = 'search'

urlpatterns = [
    path('search/', views.Search.as_view(model=Article), {'location': 'post-search', 'title': 'Search'},
         name='search'),

]

mysite/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap


urlpatterns = [
    path('sitemap.xml', sitemap, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('project.apps.search.urls')),
    path('', include('project.apps.blog.urls')),
    path('', include('project.apps.myauth.urls')),
    path('', include('project.apps.account.urls')),
    path('', include('project.apps.chat.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('api/', include('project.apps.delete_app.urls')),
    path('api/', include('project.apps.ajax_utils.urls')),
    path('api/', include('project.apps.like_dislike.urls')),
    path('api/', include('project.apps.comments.urls')),
    path('api/', include('project.apps.autocomplete.urls'))

]

urlpatterns += i18n_patterns(path('info/', include('project.apps.info.urls')))

mysite/project/apps/blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from project.apps.like_dislike.models import Like, Subscribe
from .utils import make_thumbnail

from os.path import splitext


class BaseArticle(models.Model):
    create_data = models.DateTimeField(_('Create data'), default=timezone.now)
    last_modify_data = models.DateTimeField(_('Last modify data'), default=timezone.now)
    is_active = models.BooleanField(_('Is active'), default=True)

    @classmethod
    def from_db(cls, db, field_names, values):
        instance = super().from_db(db, field_names, values)
        instance._image_values = values[field_names.index('image')]
        return instance

    def save(self,  *args, **kwargs):
        if self.image:
            if self._state.adding or self._image_values != self.image:
                text, ex = splitext(self.image.name.lower())
                if ex != '.gif':
                    make_thumbnail(self.image, (self.max_width, self.max_height))
        super().save(*args, **kwargs)
        for hashtag in do_hashtags(self.text):
            tag, stat = Tag.objects.get_or_create(name=hashtag, defaults={'name': hashtag})
            self.tags.add(tag)


    def _save(self,  *args, **kwargs):
        super().save(*args, **kwargs)

    def _delete(self):
        self.is_active = False
        self._save(update_fields=['is_active'])

    def _return(self):
        self.is_active = True
        self._save(update_fields=['is_active'])

    class Meta:
        abstract = True

############################################################################

class TagManger(models.Manager):
    def top_tags(self):
        return self.annotate(sort=models.Count('article')).order_by('-sort')[:10]

class Tag(models.Model):
    create_data = models.DateTimeField(_('Create data'), default=timezone.now)
    name = models.CharField(_('Name'), max_length=44, unique=True)

    objects = TagManger()

    def popular(self):
        return self.article_set.count()

    def __str__(self):
        return self.name


#############################################################################


from .utils import do_hashtags

class ArticleManager(models.Manager):


    def loader(self, req, location):
        objs = self.filter(is_active=True)
        f, q = req.GET.get('f'), req.GET.get('q')
        if f:
            objs = objs.filter(**{location.field:f})
        if q:
            objs = objs.filter(text__icontains=q)
        return objs



class Article(BaseArticle):

    max_width = settings.MAX_WIDTH_IMG
    max_height = settings.MAX_HEIGHT_IMG

    text = models.TextField(_('Text'), max_length=settings.MAX_POST_SIZE,  null=True, blank=True)
    views = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name=_('Views'), blank=True, related_name='article_set_views')
    image = models.ImageField(_('Image'), upload_to='post_img/', null=True, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name=_('Tags'), blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Author'), on_delete=models.CASCADE)
    like = GenericRelation(Like, verbose_name=_('Like'), related_query_name='article')

    objects = ArticleManager()

    def viewed(self, user):
        if not self.views.filter(username=user.username).exists():
            self.views.add(user)

    def get_absolute_url(self):
        return reverse('account:profile-post', kwargs={'login': self.author.username, 'init': self.id})


    @property
    def get_user(self):
        return self.author

    class Meta:
        ordering = ['-id']

mysite/project/apps/blog/forms.py
from django.forms import ModelForm, widgets, ValidationError
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.utils import timezone

from .models import Article

from os.path import splitext
import logging

logger = logging.getLogger(__name__)

class BaseCreateForm(ModelForm):

    def clean_image(self):
        if getattr(self.cleaned_data['image'], 'image', None):
            if self.cleaned_data['image'].size > (1000 * 1000):
                raise ValidationError(_('You can upload an image in JPG, GIF or PNG formats. Max size file 1mb'))
            file, ext = splitext(self.cleaned_data['image'].name.lower())
            if ext not in ('.jpeg', '.jpg', '.png', '.gif'):
                raise ValidationError('Неподдерживаемый формат')

        return self.cleaned_data['image']


class CreatePostForm(BaseCreateForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['text'].widget = widgets.Textarea(attrs={'Class': 'form-control',
                                                              'rows': 6, 'style':
                                                              'resize:none; font-size: 14px',
                                                              'maxlength': settings.MAX_POST_SIZE,
                                                              'id': 'navbar-create_post_form'})

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('image') and not cleaned_data.get('text'):
            raise ValidationError('((Nothing))')
        return cleaned_data

    class Meta:
        model = Article
        fields = ['text', 'image']



class UpdatePostForm(CreatePostForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['text'].widget = widgets.Textarea(attrs={'Class': 'form-control',
                                                              'style':
                                                              'box-shadow: none; resize:none; font-size: 14px',
                                                              'maxlength': settings.MAX_POST_SIZE,
                                                              'id': 'update-post-text',
                                                               'rows': ''})

    def clean(self):
        cleaned_data = super().clean()
        expired = self.instance.create_data + timezone.timedelta(hours=24)
        if timezone.now() > expired:
            logger.error('Change error: Date %s, Now %s' % (expired, timezone.now()))
            raise ValidationError('Time expired')
        return cleaned_data

mysite/project/apps/blog/views.py
from django.template.loader import render_to_string
from django.views.generic import CreateView, DetailView, TemplateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST


from project.apps.ajax_utils_.mixins import AjaxMixin
from project.apps.ajax_utils.mixins import AjaxLoaderMixin
from project.apps.account.utils import get_user_recommends
from project.apps.account.mixins import OnlyOwnerMixin
from .mixins import CacheMixin
import logging

logger = logging.getLogger(__name__)


class MainPage(AjaxLoaderMixin, CacheMixin, TemplateView):
    cache_time = 5

    def get_location(self):
        return reverse('blog:main_page')


class DetailArticle(AjaxMixin,  DetailView):

    def post(self, req, **kwargs):
        post = self.get_object()
        if req.user.is_authenticated:
            post.viewed(req.user)
        return self.get_json(req, extra={'url': post.get_absolute_url()}, objs=(post,))


@method_decorator(require_POST, name='dispatch')
class CreateArticle(LoginRequiredMixin, AjaxMixin, CreateView):

    def post(self, req, *args, **kwargs):
        self.path = req.POST.get('path')
        return super().post(req, *args, **kwargs)

    def get_data(self, form):
        context = {'html': render_to_string('blog/publish.html'), 'add': False}
        user_home = reverse('account:profile', kwargs={'login': self.request.user.username})
        if user_home == self.path:
            context.update({'post': render_to_string('blog/articles.html',
                                                     {'objs': (self.object,)},
                                                     self.request),
                                                     'add': True})
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        return response


class UpdateArticle(OnlyOwnerMixin, AjaxMixin, CacheMixin, UpdateView):

    def get_data(self, form):
        return {'html': render_to_string('blog/articles.html', {'objs': (self.object,)}, self.request)}

    def get(self, req, *args, **kwargs):
        self.object = self.get_object()
        return self.get_json(req, **self.get_context_data())

    def form_valid(self, form):
        if self.request.POST.get('delete'):
            form.instance.image = None
        self.delete_cache('post', [str(self.object.id)])
        return super().form_valid(form)



class Recommend(AjaxMixin, View):
    template_name = 'tag/home_sidebar.html'

    def get(self, req, **kwargs):
        return self.get_json(req, **get_user_recommends(req.user, req, 30))

mysite/project/apps/blog/templates/tag/about-sidebar.html
{% load static %}

<div class="card bg-light border-0" style="width: 18rem;">

      <div class="card-body py-2 px-0">
          <ul class="nav">
              <li class="nav-item">
                  <a href="{% url 'info:dispatch' 'about' %}" class="nav-link text-muted py-1" style="font-size: 11px"><strong>About</strong></a>
                  <a href="{% url 'info:dispatch' 'privacy_policy' %}" class="nav-link text-muted py-1" style="font-size: 11px"><strong>Privacy policy</strong></a>
              </li>
              <li class="nav-item">
                   <a href="{% url 'info:dispatch' 'help' %}" class="nav-link text-muted py-1" style="font-size: 11px"><strong>Help</strong></a>
                  <a href="{% url 'info:dispatch' 'contacts' %}" class="nav-link text-muted py-1" style="font-size: 11px"><strong>Contacts</strong></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-muted py-1" href="{% url 'info:dispatch' 'support' %}" style="font-size: 11px"><strong>Support</strong></a>
                  <a class="nav-link text-muted py-1" style="font-size: 11px"><strong>Language</strong></a>
              </li>
          </ul>
      </div>
</div>

mysite/project/apps/blog/templates/tag/edit_button.html
{% load i18n %}

{% if edit %}
<a class="dropdown-item btn" data-action="update_object" data-id="{{ post.id }}">{% trans "Edit" %}</a>

{% endif %}

mysite/project/apps/blog/templates/tag/form_post.html
{% load static %}


<div class="modal fade bd-example-modal-lg px-2" tabindex="-1" id="Create-post" role="dialog" aria-labelledby="Create-postTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div id="post-create-success" class="text-success">


        </div>
        <div id="content-creation-post">
      <div class="modal-header pt-1 pb-1 border-light">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <div class="modal-body">

        <div class="form-group">
    {{ form.text }}
            <a class="text-danger" id="post-create-error-text"></a>
            <ul class="nav justify-content-left pt-2">
                <li class="nav-item">
                    <h6 id="count_message">0 </h6>
                </li>
                <li class="nav-item pl-1">
                    <h6> - {{ max_length }} </h6>
                </li>
            </ul>
        </div>
    <label class="btn btn-outline-primar" for="image-post-input">
        <img id="holder-image-load" class="ml-1 btn-outline-primar" width='35' src="{% static 'blog/img/baseline-add_photo_alternate-24px(3).svg' %}" data-toggle="tooltip" data-placement="top" title="Change image">
        <input type='file' onchange="readURL(this);"  id="image-post-input" name="{{ form.image.html_name }}" style="display:none">
    </label>
        <a class="text-danger" id="post-create-error-img"></a>
        <button class="btn btn-outline-info" id="send-form-post" style="display:none">Опубликовать</button>

    </div>
        <div class="row">
            <div class="col-lg-3 col-md-4 col-6">
                <div id="wrapper-image-load-post" style="display:none">
                    <button type="button" class="close" onclick="close_file_choice()">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <img id="image-load-post" class="img-fluid img-thumbnail" style="max-height: 200px">
                </div>
            </div>
        </div>
    </div>
  </div>
  </div>
</div>



<script src="{% static 'blog/js/image_loader.js' %}"></script>

mysite/project/apps/blog/templates/tag/home_sidebar.html
{% load static %}
{% load like_tag %}
{% load account_tags %}
{% load i18n %}

<div class="card mt-3" style="width: 18rem;">

      <div class="card-body">
          <h6 class="card-title"><strong>{% trans "People you may be interested in" %}</strong></h6>
{% for user in objs %}
          <ul class="nav">
              <li class="nav-item">
                  <div class="card-comm-side-avatar ">
                      <a href="{{ user.get_absolute_url }}"><img class="comm-side-Photo" src="{% user_image user.profile 't' %}"></a>
                  </div>
              </li>
              <li class="nav-item">
                  <a href="{{ user.get_absolute_url }}" class="text-dark"> <h6 class="pl-2 pt-2">{{ user.username }}</h6></a>
              </li>
          </ul>
          <hr class="py-0 my-1">
{% endfor %}
          <a class="text-muted btn" data-action="show-more-recommend">Show more...</a>
      </div>
</div>

mysite/project/apps/blog/templates/tag/modal-notify.html
{% load static %}
{% load i18n %}

<div class="modal fade" id="modal-notify-window" tabindex="-1" role="dialog" aria-labelledby="modal-notify-window" aria-hidden="true">
  <div class="modal-dialog modal-lg w-50" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" data-id="title-dialog-notify"> {{ user.username }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"  id="close-user-dialogs">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pt-1 pb-0" id="list-dialogs-notify-body">

      </div>

      <div class="modal-footer align-self-center py-1" id="button-dialogs-div" data-id="{{ user.pk }}">
        <button type="button" style="display:none" id="button-dialogs-notify-action" class="btn btn-outline-danger align-self-center btn-sm py-0">{% trans "load more" %}</button>
      </div>

    </div>
  </div>
</div>

mysite/project/apps/blog/templates/tag/navbar.html
{% load static %}
{% load blog_tags %}
{% load account_tags %}
{% load i18n %}


{% if user.is_authenticated %}
    {% my_notify user %}
    {% post_form %}
    <script src="{% static 'ajax_utils/js/ajax-post.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'autocomplete/css/autocomplete.css' %}">
    <nav class="navbar navbar-expand-lg navbar-light  sticky-top mb-0 pb-0 pt-0 pr-0" id="navbar" style="background-color: #e3f2fd;">
        <a href="/" class="navbar-brand">
            Logo
        </a>
        <div class="collapse navbar-collapse pl-2" id="navbarToggler">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="py-0 text-dark my_link {% if loc == 'home' %} my_active {% endif %}" href="/home/">Home</a>
                </li>
                <li class="nav-item px-2">
                    <a class="py-0 text-dark my_link {% if loc == 'public' %} my_active {% endif %}" href="/">Public</a>
                 </li>
                <li class="nav-item pl-3">
                     <form class="form-inline  my-lg-0 pr-5" id="form-search">
                         <input class="form-control mr-sm-2 pr-5" type="search" maxlength="30" placeholder="Hmm..." id="id_input" aria-label="input">
                    </form>
                </li>
            </ul>
                <nav class="navbar p-1 ml-2">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Create-post">
                        {% trans "What's new?" %}
                    </button>
                </nav>
                <nav class="navbar pt-2 p-1 ml-2">
                    <a type="button" class="btn" data-action="load-modal-notifications" data-type="dialog/user-dialogs">
                        <small class=" mr-5  position-absolute"><span class="badge badge-danger p-1 mt-0" id="counter-message" style="font-size: 9px;">{% msg_count user id_dialog %}</span></small>
                            <img  class="ml-1" src="{% static 'blog/img/baseline-mail_outline-24px.svg' %}">
                        <input type="hidden" id="message-dispatch" value="">
                    </a>
                </nav>
            <nav class="navbar p-1 ml-2">
                <a type="button" class="btn" data-action="load-modal-notifications" data-type="notify/user-notify">
                    <small class=" mr-5  position-absolute"><span class="badge badge-danger p-1 mt-0" id="counter-notify"  style="font-size: 9px;">{% notify_count user %}</span></small>
                    <img  class="ml-1" src="{% static 'blog/img/baseline-notification_important-24px.svg' %}">
                </a>
            </nav>
                <ul class="navbar-nav mr-0">
                    <li class="nav-item dropdown">
                        <button class="btn btn-light dropdown-toggle pr-4" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.profile.pref_name }}
                            <img src="{% user_image user.profile 't' %}" class="rounded-circle" width="35" height="35">
                         </button>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'account:profile' user.profile.name %}">My page</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account:profile-settings' %}">Settings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'myauth:logout' %}">Logout</a>
                         </div>
                    </li>
                </ul>
        </div>
    </nav>


    <script src="{% static 'ajax_utils/js/loader_dialogs.js' %}"></script>
    <script src="{% static 'chat/js/list-dialogs.js'%}"></script>
    <script src="{% static 'event_handler/js/websocket_event_handler.js' %}"></script>

{% else %}
    <nav class="navbar navbar-expand-lg navbar-light  sticky-top mb-0 pb-0 pt-0 pr-0" style="background-color: #e3f2fd;">
        <a href="/" class="navbar-brand">
            <div class="collapse navbar-collapse pl-2" id="navbarToggler">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item pl-3">
                        <a class="dropdown-item" href="{% url 'myauth:login' %}">Login</a>
                    </li>
                    <li class="nav-item pl-3">
                     <form class="form-inline  my-lg-0 pr-5" id="form-search">
                         <input class="form-control mr-sm-2 pr-5" type="search" maxlength="30" placeholder="Hmm..." id="id_input" aria-label="input">
                    </form>
                </li>
                </ul>
            </div>
    </nav>
{% endif %}
 <script src="{% static 'autocomplete/js/autocomplete.js' %}"></script>

mysite/project/apps/blog/templates/tag/post.html
{% load static %}
{% load i18n %}

 <link rel="stylesheet" type="text/css" href="{% static 'comments/css/comment.css' %}">

<div class="modal fade" id="detail-post-container" tabindex="-1" role="dialog" aria-labelledby="detail-post-container" aria-hidden="true">
  <div class="modal-dialog modal-lg w-50  modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body pt-1 pb-0" id="detail-post-container-body">
      </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12" style="background-color: #ffffff">
                {% if user.is_authenticated %}
                    <div class="form-group mt-2">
                        {{ form_comment.text }}
                        <input type="hidden" value="">
                        <input data-action="comment-send" type="button" class="btn btn-link" value="{% trans 'Send' %}"/>
                    </div>
                {% endif %}
                 <hr class="pb-0 mb-0">
            </div>
        </div>
    </div>
        <div class="container-fluid">
            <div id="container-comments" class="mt-1 pb-2">
            </div>
        </div>
        <div class="modal-footer align-self-center py-1">
            <button type="button" id="button-comments-loader" class="btn btn-outline-danger align-self-center btn-sm py-0" style="display: none">{% trans "load more" %}</button>
      </div>
    </div>
  </div>
</div>


<script src="{% static 'blog/js/detail_post.js' %}"></script>
<script src="{% static 'comments/js/answer_comment.js' %}"> </script>

mysite/project/apps/blog/templates/tag/tags.html
{% load static %}
{% load humanize %}
{% load i18n %}

  <div class="card" style="width: 18rem;">

      <div class="card-body">
    <h5 class="card-title">{% trans "Popular now" %} </h5>
{% for tag in tags %}
          <ul class="nav ">
              <li class="nav-item">
                  <strong><a href="{% url 'search:search' %}?q={{ tag.name }}" class="text-info">#{{ tag.name }}</a></strong>
                  <small><p class="text-muted mb-0">{{ tag.popular|intword }} {% trans "Posts" %}</p></small>
              </li>
          </ul>
          <hr class="py-0 my-1">
{% endfor %}
      </div>
</div>