mysite/project/apps/info/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views, forms

app_name = 'info'

urlpatterns = [
    path('load_template/<path:url>/', views.Info.as_view()),
    path('send/message/', views.QuestionView.as_view(template_name='info/site_form.html',
                                                     form_class=forms.QuestionForm),
                                                    {'type': 'msg'}, name='send-message'),
    path('send/email/', views.QuestionView.as_view(template_name='info/email_form.html',
                                                   form_class=forms.QuestionFormEmail),
                                                    {'type': 'email'}, name='send-email'),

    path('<path:url>/', views.Info.as_view(template_name='info/info-main.html'), {'title': 'info'}, name="dispatch"),

]

mysite/project/apps/myauth/urls.py
from django.urls import path
from . import views
from .forms import MyPasswordResetForm, MySetPasswordForm,  MyLoginForm, ActivEmail, MyRegForm
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth import get_user_model

app_name = 'myauth'

urlpatterns = [

    path('login/', views.Login.as_view(template_name = 'myauth/registration.html',
                                       form_class = MyLoginForm),
                                        {'title': 'Login'},
                                        name='login'),

    path('registration/', views.Registr.as_view(template_name = 'myauth/registration.html',
                                        form_class = MyRegForm,
                                        model=get_user_model(),
                                        success_url='/'),
                                        {'title': 'Registration'},
                                        name='registration'),

    path('login/password-reset/', views.ResetPass.as_view(success_url = '/login/',
                                        email_template_name='back_task/reset_mail.html',
                                        html_email_template_name='back_task/reset_mail.html',
                                        form_class=MyPasswordResetForm)),

    path('login/help/', views.HelpLogin.as_view(template_name = 'myauth/help.html',
                                        form_class = ActivEmail,
                                        success_url='/login/help/'),
                                        {'title': 'Help'},
                                        name='login-help'),

    path('login/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                        template_name = 'myauth/reset_pass_form.html',
                                        success_url='/login/',
                                        form_class=MySetPasswordForm),
                                        name='password_reset_confirm'),

    path('logout/', views.Logout.as_view(template_name = 'myauth/registration.html',
                                        next_page = '/'),
                                        name='logout'),
    path('verify/<uuid:uuid>/', views.Vertify_account.as_view(), name='verify'),



]

mysite/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap


urlpatterns = [
    path('sitemap.xml', sitemap, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('project.apps.search.urls')),
    path('', include('project.apps.blog.urls')),
    path('', include('project.apps.myauth.urls')),
    path('', include('project.apps.account.urls')),
    path('', include('project.apps.chat.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('api/', include('project.apps.delete_app.urls')),
    path('api/', include('project.apps.ajax_utils.urls')),
    path('api/', include('project.apps.like_dislike.urls')),
    path('api/', include('project.apps.comments.urls')),
    path('api/', include('project.apps.autocomplete.urls'))

]

urlpatterns += i18n_patterns(path('info/', include('project.apps.info.urls')))

mysite/project/apps/myauth/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import render_to_response
from django.utils.translation import gettext_lazy as _

import logging

logger = logging.getLogger(__name__)

class BanList(models.Model):
    ban_24h_template = 'account/ban_24.html'
    ban_15m_template = 'account/ban_15.html'

    ban = models.BooleanField(_('Ban'), default=False)
    attempts = models.IntegerField(_('Attempts'), default=0)
    time_unblock = models.DateTimeField(_('Time unblock'), default=timezone.now)
    ip = models.GenericIPAddressField(_('ip'))

    def __str__(self):
        return 'stat-{}: attempt-{}: time-{}: {}'.format(self.ban, self.attempts, self.time_unblock, self.ip)

    def banned(self):
        self.attempts += 1
        if self.attempts in [6, 9, 12]:
            self.time_unblock = timezone.now() + timezone.timedelta(minutes=15) \
                if self.attempts in [6, 9] else timezone.now() + timezone.timedelta(hours=24)
            self.ban = True
        elif self.attempts > 12:
            self.attempts = 1
        self.save()

    def check_ban(self):
        if self.ban and timezone.now() < self.time_unblock:
            if self.attempts in [6, 9, 12]:
                template = self.ban_15m_template if self.attempts in [6, 9] else self.ban_24h_template
                logger.warning('Try auth. Acquire ban %d, ip-%s' % (self.attempts, self.ip))
                return {'status': 'ban', 'response': render_to_response(template)}
        elif self.ban and timezone.now() > self.time_unblock:
            self.ban = False
            self.save(update_fields=['ban'])
            logger.warning('Try auth. Release, ip-%s' % self.ip)
        return {'status': 'ok'}

    def ban_15m(self):
        self.time_unblock = timezone.now() + timezone.timedelta(minutes=15)
        self.save(update_fields=['time_unblock'])

    def ban_24h(self):
        self.time_unblock = timezone.now() + timezone.timedelta(hours=24)
        self.save(update_fields=['time_unblock'])


from django.contrib import admin


class BanListAdmin(admin.ModelAdmin):
    list_display = ('ip', 'ban', 'attempts', 'time_unblock')
    search_fields = ('ip_address',)

mysite/project/apps/myauth/forms.py
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from project.apps.back_task.tasks import sendler_mail
from django.template.loader import render_to_string
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.forms import widgets
from django import forms
from django.utils.translation import gettext as _

import logging
logger = logging.getLogger(__name__)

class MyRegForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({'Class': 'form-control',
                                                    'placeholder': 'Email',
                                                    })

        self.fields['username'].widget = widgets.TextInput(attrs={'Class': 'form-control',
                                                                  'placeholder': 'Login'})

        self.fields['username'].help_text += ' And length login minimum  characters'

        self.fields['username'].label = 'Login'
        self.fields['password1'].widget = widgets.PasswordInput(attrs={'Class': 'form-control',
                                                                  'placeholder': 'Password'})
        self.fields['password2'].widget = widgets.PasswordInput(attrs={'Class': 'form-control',
                                                                   'placeholder': 'Password agan'})



    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields =['username', 'email']

    def clean_username(self):
        if len(self.cleaned_data['username']) < 3:
            raise forms.ValidationError(_('Too short!. 3 characters minimum'))
        return self.cleaned_data['username']


    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError(_('Requared'))
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError(_('User with this email already exists'))
        return self.cleaned_data['email']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.save()
        logger.info('User registered! %s' % user.username)
        return user


class MyLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = widgets.TextInput(attrs={'Class': 'form-control',
                                                                  'placeholder': 'Login',
                                                                  'id': 'login_username'})
        self.fields['password'].widget = widgets.PasswordInput(attrs={'Class': 'form-control',
                                                                       'placeholder': 'Password'})

    def clean_username(self):
        model = get_user_model()
        try:
            user = model.objects.get(username=self.cleaned_data.get('username'))
        except model.DoesNotExist:
            raise self.get_invalid_login_error()
        if not user.is_verified:
            id = user.id
            raise forms.ValidationError(_('User not verified,'
                                        ' please check email'), code='not verify', params={'id': id})
        if not user.is_active:
            raise forms.ValidationError(_('User was deleted'))
        return self.cleaned_data['username']





class MyPasswordResetForm(PasswordResetForm):

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        subject = render_to_string(subject_template_name, context)
        subject = ''.join(subject.splitlines())
        body = 'Reset mail'
        context.update(user='')
        sendler_mail.delay(subject, body, from_email, [to_email], template_name=html_email_template_name, **context)

class MySetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'Class': 'form-control col-6',
                                                     'placeholder': 'Password',
                                                     })
        self.fields['new_password2'].widget.attrs.update({'Class': 'form-control col-6',
                                                     'placeholder': 'Password again',
                                                     })
class ActivEmail(forms.Form):

    email = forms.EmailField(required=True)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'Class': 'form-control',
                                                    'placeholder': 'Email',
                                                    })

mysite/project/apps/myauth/views.py
from django.urls import reverse
from django.template.loader import render_to_string
from django.views.generic import CreateView, RedirectView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LogoutView, LoginView
from django.conf import settings
from django.contrib.auth.views import PasswordResetView
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404

from project.apps.account.mixins import NotLoginRequiredMixin
from project.apps.ajax_utils_.mixins import AjaxMixin
from .models import BanList
from .forms import MyRegForm
from .utils import handler_ip, set_geo
from project.apps.back_task.tasks import sendler_mail


@method_decorator(require_POST, name='dispatch')
class Registr(NotLoginRequiredMixin, AjaxMixin, CreateView):
    captcha = True

    def get_data(self, form):
        return {'html': render_to_string('myauth/verify.html', {'user': form.instance.username,
                                                                            'mail': form.instance.email})}


class Login(NotLoginRequiredMixin, LoginView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reg_form'] = MyRegForm()
        return context

    def post(self, req, *args, **kwargs):
        self.ip = handler_ip(req)
        self.ban_list, created = BanList.objects.get_or_create(ip=self.ip, defaults={'ip': self.ip})
        status = self.ban_list.check_ban()
        return super().post(req, *args, **kwargs) if status['status'] == 'ok' else status['response']

    def form_valid(self, form):
        self.ban_list.delete()
        return super().form_valid(form)

    def form_invalid(self, form):
        self.ban_list.banned()
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('account:profile', kwargs={'login': self.request.user.username})


class Logout(LogoutView): pass


class Vertify_account(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        user = get_object_or_404(get_user_model(), uuid=self.kwargs['uuid'], is_verified=False)
        user.is_verified = True
        user.save(update_fields=['is_verified'])
        set_geo(user, self.request)
        self.url = reverse('myauth:login')
        return super().get_redirect_url(*args, **kwargs)



@method_decorator(require_POST, name='dispatch')
class ResetPass(AjaxMixin, PasswordResetView):
    def get_data(self, form):
        return {'html': render_to_string('myauth/reset_pass.html', {'email': form.cleaned_data['email']})}

from django.views.generic import FormView


class HelpLogin(NotLoginRequiredMixin, AjaxMixin, FormView):
    captcha = True

    def get_data(self, form):
        return {'email': form.cleaned_data['email']}

    def form_valid(self, form):
        res = super().form_valid(form)
        if res.status_code == 200:
            user = get_user_model().objects.filter(email=form.cleaned_data['email'])
            if user and not user.first().is_verified:
                user = user.first()
                kwargs = {'link': 'http://localhost%s' % reverse('myauth:verify', kwargs={'uuid': user.uuid}),
                          'user': user.username}
                sendler_mail.delay('', '', settings.DEFAULT_FROM_EMAIL, [user.email],
                                   template_name='back_task/mail_registr.html', **kwargs)
        return res

mysite/project/apps/myauth/templates/myauth/ban_15.html
{% extends "blog/MainPage.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block body %}


<div class="card text-center">
  <div class="card-header">
    {% trans "Due to suspicious actions, we have blocked your ip-address" %}
  </div>
  <div class="card-body">
    <p class="card-text">{% trans "You will be able to log in to your account after 15 minutes or use authorization through social networks." %}</p>
  </div>
</div>

{% endblock %}


{% block sidebar %}
{% endblock %}

{% block event_hidden %}
{% endblock %}


{% block buttom %}
{% endblock %}

mysite/project/apps/myauth/templates/myauth/ban_24.html
{% extends "blog/MainPage.html" %}
{% load i18n %}

{% block head %}
{% endblock %}

{% block body %}


<div class="card text-center">
  <div class="card-header">
    {% trans "Due to suspicious actions, we have blocked your ip-address" %}
  </div>
  <div class="card-body">
    <p class="card-text">{% trans "You will be able to log into your account after 24 hours or use authorization through social networks." %}</p>
  </div>
</div>

{% endblock %}


{% block sidebar %}
{% endblock %}

{% block event_hidden %}
{% endblock %}


{% block buttom %}
{% endblock %}

mysite/project/apps/myauth/templates/myauth/help.html
{% extends "blog/MainPage.html" %}
{% load static %}
{% load i18n %}

{% block head %}
<script src='https://www.google.com/recaptcha/api.js'></script>
 <script src="{% static 'ajax_utils/js/ajax-post.js' %}"></script>
{% endblock %}

{% block body %}

<div class="row  pt-5 mt-0 ">
    <div class="col-sm-12 border" style="background-color: #ffffff; height: 400px">
    <p><a class="btn" href="{% url 'myauth:login' %}"> < Login</a></p>
    <button class="btn btn-link mt-4" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    {% trans "Did not receive a letter with a link to account activation?" %}
    </button>

<div class="collapse" id="collapseExample">
  <div class="card card-body">
      <div id="body-activate-email">
     <div class="form-group">
         <label for="id_email">
             {% trans "Enter the email to which your account was registered, we will send you a new letter to activate" %}
         </label>
         {{ form.email }}
                 <button class="btn btn-primary mt-3" id="send-activate">{% trans "Send" %}</button>
         </div>
      <div class="form-group">
                <div class="g-recaptcha" data-sitekey="6LenZoQUAAAAAC5tKBi0fHFZaZnpADswyZcqEEqE"></div>
          </div>
      </div>
      <small id="error-captcha" data-type="error" class="form-text text-danger"></small>
      <small id="error-email" data-type="error" class="form-text text-danger"></small>
      <small id="info-success"  class="form-text text-success"></small>

  </div>
</div>
        <hr class="my-0">
    </div>
</div>

{% endblock %}


{% block sidebar %}
{% endblock %}

{% block event_hidden %}
{% endblock %}


{% block buttom %}
 <script src="{% static 'myauth/js/help.js' %}"></script>
{% endblock %}

mysite/project/apps/myauth/templates/myauth/registration.html
{% extends "blog/MainPage.html" %}
{% load blog_tags %}
{% load static %}
{% load i18n %}

{% block head %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="{% static 'ajax_utils/js/ajax-post.js' %}"></script>

<div class="modal fade" id="regModal" tabindex="-1" role="dialog" aria-labelledby="regModallLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <strong><h5 class="modal-title">{% trans "Registration" %}</h5></strong>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body" id="registration-body-modal">
          {% for field in reg_form %}
           <div class="form-group">
                {{ field }}
               <small id="error-{{ field.html_name }}" data-type="info-error" class="form-text text-danger"> </small>
           </div>
        {% endfor %}
          <div class="form-group">
                <div class="g-recaptcha" data-sitekey="6LenZoQUAAAAAC5tKBi0fHFZaZnpADswyZcqEEqE"></div>
          </div>
         <small id="error-captcha" class="form-text text-danger" data-type="info-error"></small>
          <small class="text-muted pr-2">{% trans "Registation via social network" %}:</small><a href='{% url "social:begin" "vk-oauth2" %}'><img src="{% static 'myauth/img/120px-VK.com-logo.svg.png' %}" width="40" height="40" data-toggle="tooltip" ></a>
      </div>
      <div class="modal-footer">
          <div class="form-group">
        <button type="button" class="btn btn-primary" id="btn-registr">{% trans "Registration" %}</button>
          </div>
      </div>

    </div>
  </div>
</div>


<div class="modal fade"  tabindex="-1" role="dialog" id="forgot-pass-modal" aria-labelledby="modal-forgot-pass" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header py-1">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body border" id="reset-password-body">
                    {% trans "We will send you a letter with a link to change your password." %}
          <div class="modal-footer border-0">
          <input type="email" class="form-control" maxlength="50" placeholder="Введите свой email" id="forgot-pass-input">
              <button class="btn btn-outline-info" id="forgot-pass-btn">{% trans "Search" %}</button>
          </div>
        </div>
  </div>
</div>
</div>

{% endblock %}




{% block body %}
<div class="row  pt-5 ">
    <div class="col-sm-12 border" style="background-color: #ffffff">
        <ul class="nav pt-1 flex-column">
            <li class="nav-item pb-1">
                <small class="text-muted float-right">{% trans "Login via social network" %}</small>
            </li>
            <li class="nav-item">
                <strong>  <a>Log in or</a></strong>
                <button type="button" class="btn btn-outline-info"  data-toggle="modal" data-target="#regModal">
                    join
                </button>
                <a class="float-right" href='{% url "social:begin" "vk-oauth2" %}'><img src="{% static 'myauth/img/120px-VK.com-logo.svg.png' %}" width="40" height="40" data-toggle="tooltip" ></a>
            </li>
        </ul>
      <hr>
    <div id="body-login">
<form method="POST">
    {% for field in form %}
 <div class="form-group">
        {{ field.label }}
        {{ field }}
       <small id="loginerror" class="form-text text-danger">   {{ field.errors}} </small>
  <small id="loginHelp" class="form-text text-muted"> {{ field.help_text }} </small>
  </div>
    {% endfor %}
{% csrf_token %}
<input type="hidden" name="next" value="/">
  <button type="submit" id="button_login" class="btn btn-primary ">Login</button>
</form>
    <small id="error" class="form-text text-danger">   {{ form.non_field_errors  }} </small>
          </div>
        <hr class="mb-0">
      <button type="button" class="btn btn-link"  data-toggle="modal" data-target="#forgot-pass-modal">
         {% trans "Forgot password?" %}
      </button>
        <a href="{% url 'myauth:login-help' %}">{% trans "Help login?" %}</a>
      </div>
</div>
{% endblock %}

{% block sidebar %}
<div class="col-lg-4 col-sm-4 d-none d-lg-block  ml-5">
        <div class="bg-white col-4 border-left border-right" style="height: 100vh; width: 23rem; position: fixed">
            <ul class="navbar-nav text-center pt-3">
                <li class="nav-item pt-2 border-bottom">
                    <a href="{% url 'info:dispatch' 'about' %}"><h3 class="text-info"> <strong>{% trans "About" %}</strong></h3></a>
                </li>

            </ul>
            </div>

</div>
{% endblock %}

{% block buttom %}
<nav class="navbar fixed-bottom navbar-light bg-light border">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="px-3" href="{% url 'info:dispatch' 'help' %}">{% trans "Help" %}</a>
            <a class="px-3" href="{% url 'info:dispatch' 'privacy_policy' %}">{% trans "Privacy policy" %}</a>
            <a class="px-3" href="{% url 'info:dispatch' 'contacts' %}">{% trans "Contacts" %}</a>
            <a class="px-3" href="{% url 'info:dispatch' 'support' %}">{% trans "Support" %}</a>
        </li>
    </ul>
</nav>
<script src="{% static 'myauth/js/reg.js' %}"></script>
{% endblock %}

mysite/project/apps/myauth/templates/myauth/reset_pass.html
{% load i18n %}

<div class="card text-center">
  <div class="card-body">
    <p class="card-text"> {% trans "We sent a link to reset your password to your email" %} {{ email }}</p>
  </div>
</div>

mysite/project/apps/myauth/templates/myauth/reset_pass_form.html
{% extends "blog/MainPage.html" %}
{% load i18n %}


{% block head %}
{% endblock %}

{% block body %}
{% if validlink %}
<form method="POST">
    {% for field in form %}
 <div class="form-group">
        {{ field.label }}
        {{ field }}
       <small  class="form-text text-danger">   {{ field.errors}} </small>
  <small  class="form-text text-muted"> {{ field.help_text }} </small>
  </div>
    {% endfor %}
{% csrf_token %}
<input type="hidden" name="next" value="/">
  <button type="submit" class="btn btn-primary ">{% trans "Change" %}</button>
    <hr>
</form>
{% else %}
<h1>{% trans "Link is no longer active" %}</h1>
{% endif %}
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block event_hidden %}
{% endblock %}


{% block buttom %}
{% endblock %}

mysite/project/apps/myauth/templates/myauth/verify.html
{% load i18n %}

<div class="card text-center">
  <div class="card-header">
    <strong>{% trans "Confirm your email" %}</strong>
  </div>
  <div class="card-body">
    <p class="card-text"> {{ user }} {% trans "We sent a letter to your email" %} {{ mail }}, {% trans "please follow the link in the letter and log in" %}</p>
  </div>
</div>