mysite/project/apps/myauth/urls.py
from django.urls import path
from . import views
from .forms import MyPasswordResetForm, MySetPasswordForm,  MyLoginForm, ActivEmail, MyRegForm
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth import get_user_model

app_name = 'myauth'

urlpatterns = [

    path('login/', views.Login.as_view(template_name = 'myauth/registration.html',
                                       form_class = MyLoginForm),
                                        {'title': 'Login'},
                                        name='login'),

    path('registration/', views.Registr.as_view(template_name = 'myauth/registration.html',
                                        form_class = MyRegForm,
                                        model=get_user_model(),
                                        success_url='/'),
                                        {'title': 'Registration'},
                                        name='registration'),

    path('login/password-reset/', views.ResetPass.as_view(success_url = '/login/',
                                        email_template_name='back_task/reset_mail.html',
                                        html_email_template_name='back_task/reset_mail.html',
                                        form_class=MyPasswordResetForm)),

    path('login/help/', views.HelpLogin.as_view(template_name = 'myauth/help.html',
                                        form_class = ActivEmail,
                                        success_url='/login/help/'),
                                        {'title': 'Help'},
                                        name='login-help'),

    path('login/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                        template_name = 'myauth/reset_pass_form.html',
                                        success_url='/login/',
                                        form_class=MySetPasswordForm),
                                        name='password_reset_confirm'),

    path('logout/', views.Logout.as_view(template_name = 'myauth/registration.html',
                                        next_page = '/'),
                                        name='logout'),
    path('verify/<uuid:uuid>/', views.Vertify_account.as_view(), name='verify'),



]

mysite/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap


urlpatterns = [
    path('sitemap.xml', sitemap, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('project.apps.search.urls')),
    path('', include('project.apps.blog.urls')),
    path('', include('project.apps.myauth.urls')),
    path('', include('project.apps.account.urls')),
    path('', include('project.apps.chat.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('api/', include('project.apps.delete_app.urls')),
    path('api/', include('project.apps.ajax_utils.urls')),
    path('api/', include('project.apps.like_dislike.urls')),
    path('api/', include('project.apps.comments.urls')),
    path('api/', include('project.apps.autocomplete.urls'))

]

urlpatterns += i18n_patterns(path('info/', include('project.apps.info.urls')))

mysite/project/apps/back_task/templates/back_task/mail_registr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<h1>Good day {{ user }}, Thank you for your registration.</h1>
<p>To activate your account, follow this link within 24 hours</p>
<p><a href="{{link}}">{{link}}</a></p>
<p>The letter is generated automatically and does not require a response.</p>
<p>----</p>
<p>Best regards, SignUP Team</p>
<p>http://signup.fun</p>
</body>
</html>

mysite/project/apps/back_task/templates/back_task/reset_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>title</title>
</head>
<body>


<h1>Someone asked for password reset for email {{ email }}. Follow the link below:</h1>
<a href="{{ protocol}}://{{ domain }}{% url 'myauth:password_reset_confirm' uidb64=uid token=token %}">

    {{ protocol}}://{{ domain }}{% url 'myauth:password_reset_confirm' uidb64=uid token=token %}
</a>

</body>
</html>